package conf

// PkgMap Pkg全局变量，不同服务端框架对应的包描述，默认为gin
var PkgMap = map[string]map[string]string{
	"gin": {
		"ContextType":       "*gin.Context",
		"ContextImport":     "github.com/gin-gonic/gin",
		"EngineType":        "*gin.Engine",
		"EngineImport":      "github.com/gin-gonic/gin",
		"HandleFuncType":    "gin.HandlerFunc",
		"HandleFuncImport":  "github.com/gin-gonic/gin",
		"StatusCodePackage": "http",
		"StatusCodeImport":  "net/http",
		"Return":            "",
		"ReturnType":        "",
	},
	"fiber": {
		"ContextType":       "*fiber.Ctx",
		"ContextImport":     "github.com/gofiber/fiber/v2",
		"EngineType":        "*fiber.App",
		"EngineImport":      "github.com/gofiber/fiber/v2",
		"HandleFuncType":    "fiber.Handler",
		"HandleFuncImport":  "github.com/gofiber/fiber/v2",
		"StatusCodePackage": "fiber",
		"StatusCodeImport":  "github.com/gofiber/fiber/v2",
		"Return":            "return",
		"ReturnType":        "error",
	},
	"echo": {
		"ContextType":       "echo.Context",
		"ContextImport":     "github.com/labstack/echo/v4",
		"EngineType":        "*echo.Echo",
		"EngineImport":      "github.com/labstack/echo/v4",
		"HandleFuncType":    "echo.HandlerFunc",
		"HandleFuncImport":  "github.com/labstack/echo/v4",
		"Return":            "return",
		"ReturnType":        "error",
		"StatusCodePackage": "http",
		"StatusCodeImport":  "net/http",
	},
	"hertz": {
		"ContextType":       "*app.RequestContext",
		"ContextImport":     "github.com/cloudwego/hertz/pkg/app",
		"EngineType":        "*server.Hertz",
		"EngineImport":      "github.com/cloudwego/hertz/pkg/app/server",
		"HandleFuncType":    "app.HandlerFunc",
		"HandleFuncImport":  "github.com/cloudwego/hertz/pkg/app",
		"StatusCodePackage": "consts",
		"StatusCodeImport":  "github.com/cloudwego/hertz/pkg/protocol/consts",
		"Return":            "",
		"ReturnType":        "",
	},
}
